spring.datasource.url=jdbc:mysql://localhost:3306/jwtdb
spring.datasource.username=root
spring.datasource.password=@Sh18ru06tika

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
